export * from './home-page.effects';
export * from './flash-deal-collection-page.effects';
export * from './brand-collection-page.effects';
export * from './cash-back-page.effects';
export * from './categories-page.effects';
export * from './collect-voucher-page.effects';
export * from './official-stores-page.effects';
export * from './search-page.effects';
export * from './terms-and-condition-page.effects';
