import {
  faUser,
  faSort,
  faSortUp,
  faSortDown,
  faSync,
  faEye,
  faBan,
  faTimes,
  faArrowLeft,
  faSave,
  faPlus,
  faMinus,
  faPencilAlt,
  faBars,
  faThList,
  faUserPlus,
  faRoad,
  faTachometerAlt,
  faHeart as fasHeart,
  faList,
  faBell,
  faBook,
  faHdd,
  faFlag,
  faWrench,
  faClock,
  faCloud,
  faSignOutAlt,
  faSignInAlt,
  faCalendarAlt,
  faSearch,
  faTrashAlt,
  faAsterisk,
  faTasks,
  faHome,
  faCannabis,
  faImage,
  faImages,
  faInfo,
  faInfoCircle,
  faStar,
  faCartPlus,
  faEdit,
  faMapMarkedAlt,
  faCheckCircle,
  faChevronUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronCircleLeft,
  faChevronCircleRight,
  faEnvelope,
  faFrown as fasFrown,
  faSmile as fasSmile,
  faMeh as fasMeh,
  faThumbsUp as fasThumbsUp,
  faTimesCircle,
  faCheckSquare,
  faShoppingCart,
  faExpandArrowsAlt,
  faCheck,
  faTruck,
  faShare,
  faBookmark as fasBookmark,
  faBox,
  faMoneyBill,
  // jhipster-needle-add-icon-import
} from '@fortawesome/free-solid-svg-icons';

import {
  faFrown as farFrown,
  faSmile as farSmile,
  faMeh as farMeh,
  faThumbsUp as farThumbsUp,
  faHeart as farHeart,
  faBookmark as farBookmark,
  faUser as farUser,
  faAddressBook as farAddressBook,
} from '@fortawesome/free-regular-svg-icons';

import {
  faFacebook as fabFacebook,
  faFacebookF as fabFacebookF,
  faTwitter as fabTwitter,
  faDribbble as fabDribbble,
  faGooglePlus as fabGooglePlus,
  faGooglePlusG as fabGooglePlusG,
  faCcPaypal as fabCcPaypal,
  faCcVisa as fabCcVisa,
  faCcMastercard as fabCcMastercard,
  faCcAmex as fabCcAmex,
} from '@fortawesome/free-brands-svg-icons';

export const fontAwesomeIcons = [
  faUser,
  faSort,
  faSortUp,
  faSortDown,
  faSync,
  faEye,
  faBan,
  faTimes,
  faArrowLeft,
  faSave,
  faPlus,
  faMinus,
  faPencilAlt,
  faBars,
  faHome,
  faThList,
  faUserPlus,
  faRoad,
  faTachometerAlt,
  fasHeart,
  farHeart,
  faList,
  faBell,
  faTasks,
  faBook,
  faHdd,
  faFlag,
  faWrench,
  faClock,
  faCloud,
  faSignOutAlt,
  faSignInAlt,
  faCalendarAlt,
  faSearch,
  faTrashAlt,
  faAsterisk,
  faCannabis,
  faImage,
  faImages,
  faInfo,
  faInfoCircle,
  faStar,
  faCartPlus,
  faEdit,
  faMapMarkedAlt,
  faCheckCircle,
  faChevronUp,
  faChevronDown,
  faEnvelope,
  fasFrown,
  farFrown,
  fasSmile,
  farSmile,
  fasMeh,
  farMeh,
  fasThumbsUp,
  farThumbsUp,
  faTimesCircle,
  faCheckSquare,
  faShoppingCart,
  faChevronLeft,
  faChevronRight,
  faChevronCircleLeft,
  faChevronCircleRight,
  faExpandArrowsAlt,
  faCheck,
  farHeart,
  faTruck,
  fabFacebookF,
  fabTwitter,
  fabDribbble,
  fabGooglePlusG,
  fabCcPaypal,
  fabCcVisa,
  fabCcMastercard,
  fabCcAmex,
  faShare,
  fasBookmark,
  farBookmark,
  farUser,
  faBox,
  farAddressBook,
  faMoneyBill,
];
